# Notebook 01 - Textual data Clean

This is the first notebook to be run. Here you will find informations about the text such as number of words, number of sentences, number of character and the vocabulary. It also has distributions for each text of the vocabulary per number of words and vocabulary per number of sentence. Adittionaly, we analyze the best fits for those distributions using statistical methods.

# 0. Setup

In [13]:
# Libraries

# General
import numpy as np                      # imports the Numpy library for numerical tools
import pandas as pd                     # imports the Pandas library for data manipulation and analysis

# Plotting Options
from matplotlib import pyplot as plt                           # imports the Pyplot module from the Matplotlib library for plotting
import seaborn as sns                                          # imports seaborn for plotting 
plt.rcParams['text.usetex'] = True                             # enables LaTeX rendering for text in plots
plt.rcParams['text.latex.preamble'] = r'\usepackage{amsmath}'  # LaTeX preamble

# File management
from pathlib import Path                  # imports path tools from Pathlib for working with file paths
import os                                 # imports the OS library for interacting with the operating system

# defines a function to find the project root directory by looking for a specific marker (default is 'data')
def find_project_root(start=Path.cwd(), marker='data'): 
    current = start
    while current != current.parent:
        if (current / marker).exists():
            return current
        current = current.parent
    raise FileNotFoundError("Project root not found")

PROJECT_ROOT = find_project_root() 
os.chdir(PROJECT_ROOT) # go to the root of the project 

# statiscal analysis
from scipy import stats

# tools for text processing
from tools import text_tools

We now define an element $\tt biblio$ from the $\tt bibliography$ class, defined in the script $\tt text_tools$. Said class contains the following atributes:

$ {\tt files}: \text{ file names} \\$
$ {\tt texts}: \text{ stories} $

In [3]:
biblio = text_tools.bibliography()  # defines a bibliography object
print(biblio.files )                # lists the files in the directory

['dreams_in_the_witch.txt', 'ex_oblivione.txt', 'poetry_of_gods.txt', 'doorstep.txt', 'colour_out_of_space.txt', 'iranon.txt', 'street.txt', 'arthur_jermyn.txt', 'crawling_chaos.txt', 'ulthar.txt', 'azathoth.txt', 'shadow_out_of_time.txt', 'haunter.txt', 'martins_beach.txt', 'tree.txt', 'whisperer.txt', 'moon_bog.txt', 'unnamable.txt', 'beast.txt', 'alchemist.txt', 'terrible_old_man.txt', 'nameless.txt', 'reanimator.txt', 'celephais.txt', 'gates_of_silver_key.txt', 'medusas_coil.txt', 'dagon.txt', 'picture_house.txt', 'memory.txt', 'white_ship.txt', 'erich_zann.txt', 'tomb.txt', 'temple.txt', 'he.txt', 'pickman.txt', 'silver_key.txt', 'clergyman.txt', 'old_folk.txt', 'from_beyond.txt', 'descendent.txt', 'nyarlathotep.txt', 'vault.txt', 'hypnos.txt', 'polaris.txt', 'book.txt', 'shunned_house.txt', 'pharoahs.txt', 'randolph_carter.txt', 'innsmouth.txt', 'charles_dexter_ward.txt', 'dunwich.txt', 'festival.txt', 'other_gods.txt', 'redhook.txt', 'hound.txt', 'outsider.txt', 'mountains_of_madness.txt', 'what_moon_brings.txt', 'cool_air.txt', 'lurking_fear.txt', 'sarnath.txt', 'juan_romero.txt', 'cthulhu.txt', 'beyond_wall_of_sleep.txt', 'high_house_mist.txt', 'rats_walls.txt', 'kadath.txt']

# 1. Information from the Texts

We now proceed to calculate some relevant parameters for each text. For now, we shall obtain:

1. Number of sentences;
2. Number of words;
3. Number of Characters.

We store these information in the Pandas DataFrame $\tt df\_texts$, to be saved as a $\tt .csv$ file.

In [4]:
# creating the dataframe
df_texts = pd.DataFrame()          # creates an empty dataframe
df_texts['text'] = biblio.texts.keys()  # adds the name of the stories
df_texts['file'] = biblio.files  # adds the name of the stories

# displays the dataframe
df_texts

                    text                      file
0    dreams_in_the_witch   dreams_in_the_witch.txt
1           ex_oblivione          ex_oblivione.txt
2         poetry_of_gods        poetry_of_gods.txt
3               doorstep              doorstep.txt
4    colour_out_of_space   colour_out_of_space.txt
..                   ...                       ...
62               cthulhu               cthulhu.txt
63  beyond_wall_of_sleep  beyond_wall_of_sleep.txt
64       high_house_mist       high_house_mist.txt
65            rats_walls            rats_walls.txt
66                kadath                kadath.txt

[67 rows x 2 columns]

We now add the relevant information to the DataFrame.

In [5]:
# Adding statistics 

# number of sentences
df_texts['sentence_count'] = [ len(biblio.sentences[text]) for text in df_texts['text'] ]  

# number of words
df_texts['word_count'] = [ len( biblio.texts[text].split() ) for text in df_texts['text'] ]  

# vocabulary, i.e. number of different words; 
# here, a set() object was used to filter out duplicate words
df_texts['vocabulary'] = [ len( set( biblio.texts[text].split() ) ) for text in df_texts['text'] ] 

# number of characters
df_texts['character_count'] = [ len(biblio.texts[text]) for text in df_texts['text'] ]  

# diaplays the updated DataFrame
df_texts.to_csv('data/gold/texts.csv', index=False)  # saves the DataFrame to a CSV file
df_texts.head()

,text,file,sentence_count,word_count,vocabulary,character_count
0,dreams_in_the_witch,dreams_in_the_witch.txt,546,14626,4148,86779
1,ex_oblivione,ex_oblivione.txt,21,701,348,3814
2,poetry_of_gods,poetry_of_gods.txt,56,1866,862,10560
3,doorstep,doorstep.txt,422,10446,3297,60265
4,colour_out_of_space,colour_out_of_space.txt,500,12134,3475,68090